### ISSUE TITLE
Proc tolikrat settings.gradle?

### ISSUE THREAD

**Issue by kubahorak** [vkuzel/Gradle-Multi-Project-Development-Template#1]
Cus Vasku,

nemas lepsi mit jedny settings.gradle v root projektu a pak v kazdym subprojektu jenom build.gradle, kde definujes dependencies {compile project()}?

Inspirace treba zde: https://github.com/Netflix/Hystrix

**Comment by vkuzel** [comment]
Ahoj,

jestli jsem něco nepřehlédl, tak settings.gradle mám v tomhle projektu jenom dvakrát a to právě v těch dvou root projektech. V subprojektech/modulech, které jsou v adresáři framework už settings.gradle není.

Tahle šablona by měla ukázat, že z jednoho balíčku modulů/subprojektů můžeš postavit několik root projektů, přičemž každý root projekt může využívat jenom některé z modulů, které jsou vyjmenované právě v těch settings.gradle souborech (no a taky v závislostech v build.gradle). Myšlené to je tak, že máš nějaký framework a pro klienta 1 postavíš projekt využívající jeho část, pro klienta 2 pak postavíš projekt využívající jeho jinou část.

V.

**Comment by kubahorak** [comment]
Aha, trochu me prekvapilo, ze je to v jednom repozitari, ale dava mi to ted smysl. Jako slabinu tohohle pristupu nicmene vidim to, ze nemuzes pro ruzny klienty pouzivat ruzny verze frameworku.  AFAIK se idealne pro klienty a framework delaji vlastni Git repozitare a takovyhle zavislosti na frameworcich se resi jednim ze dvou zpusobu:
- bud vlastnim Maven repozitarem, kam se uploaduji sdileny knihovny, na jejichz verze se pak odkazujes z klientskych projektu,
- nebo ze Gradle subprojekty klientskyho root projektu jsou Git submoduly primo do Git repozitare frameworku.

Tvuj pristup vidim jako hodne podobny tomu 1., akorat bez Maven repozitare a s includovanim pres "../".

**Comment by vkuzel** [comment]
Nemožnost používat různé verze frameworku je jeden z účelů, proč je to udělané takhle. Dřív se mi totiž stávalo, že jsem udělal v různých projektech změny do frameworku, které se mi pak těžko přenášely zpět do ostatních projektů pro ostatní klienty. Tímhle přístupem bych chtěl držet všechny projekty pořád aktuální. Prostě uděláš změnu, skompiluješ ostatní projekty, sjedeš testy a vydáš novou verzi.

Závislosti, přes maven repozitář se mi nelíbí, přijde mi to těžkopádné. Měli jsme to tak v minulé práci a každou chvíli jsem tam narážel na to, že jsem neměl stažené aktuální verze závislých modulů. Jejich stahování mi pak přišlo jako zbytečná činnost navíc. To, že jsou všechny projekty v jednom repozitáři, je spíš záležitost téhle šablony. V reálném světě bych chtěl mít spíš repozitář pro framework a pak repozitáře pro projekty.

O Git submodulech jsem nevěděl, na to se ještě podívám.

**Comment by kubahorak** [comment]
Ok, rozumim. Kdyby se to deployovani bejvalo spravne nastavilo, fungovalo by to tenkrat lip. Co nadelas.

Git submoduly maj tu nevyhodu, ze kdyz je pouzijes vicekrat, mas vsude kopie souboru. Pak zmeny musis pushovat a pullovat ze vzdalenyho repozitare. Tobe by se mozna mohlo hodit je pouzit pro ten framework a klientsky projekty. Nevyhoda je ale, ze musis commitnout v submodulu a pak zaevidovat zmenu hashe v rodicovskym repozitari. Pri pullu se pak musi dat pull --recursive-submodules a submodule update. Da se to ale automatizovat pomoci nastaveni gitu.
